---
title: "sim_PHE_gen"
author: "Brian S. Yandell"
date: "1/1/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Simulate PHEnotype and genotype idea.

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
```

```{r}
n <- 200
sd <- 0
ENV <- rnorm(n)
QTL_num <- round(runif(n))
poly <- rnorm(n)
err <- sd * rnorm(n)
d <- data.frame(ENV,QTL_num,poly,err)
d$PHE <- d$ENV + 2 * d$QTL_num + d$poly + d$err
d$PHE_qxe <- 2 * d$ENV * d$QTL_num + d$poly + d$err
d$PHE_gxe <- sqrt(2) * d$ENV * d$poly + 2 * d$QTL_num + d$err
```

```{r}
d <- mutate(d, QTL = c("AA","AB")[1 + round(QTL_num)])
```

```{r}
ggplot(d, aes(PHE,sort(ENV))) +
  geom_point(size=3) +
  geom_smooth(method="lm",se=FALSE)
```


```{r}
ggplot(d, aes(PHE,ENV)) +
  geom_point(size=3) +
  geom_smooth(method="lm",se=FALSE)
```


```{r}
jpeg("../../Figs/phe_qtl.jpg", width=600, height=400)
ggplot(d, aes(ENV,PHE, fill=QTL)) +
  geom_point(size=3, shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  ggtitle("model: PHE = QTL + ENV")
dev.off()
```

```{r}
jpeg("../../Figs/phe_poly.jpg", width=600, height=400)
ggplot(d, aes(ENV,PHE, fill=poly)) +
  geom_point(size=3, shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  scale_fill_gradient2() +
  ggtitle("model: PHE = poly + ENV")
dev.off()
```

```{r}
jpeg("../../Figs/phe_qtl_poly.jpg", width=600, height=400)
ggplot(d, aes(ENV,PHE, fill=poly)) +
  geom_point(size=3,shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  facet_wrap(~QTL)+
  scale_fill_gradient2() +
  ggtitle("model: PHE = QTL + poly + ENV")
dev.off()
```

```{r}
ggplot(d, aes(poly,PHE, fill=ENV)) +
  geom_point(size=3, shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  facet_wrap(~QTL)+
  scale_fill_gradient2() +
  ggtitle("QTL & poly")
```

```{r}
ggplot(d, aes(poly,ENV, fill=PHE)) +
  geom_point(size=3, shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  facet_wrap(~QTL)+
  scale_fill_gradient2() +
  ggtitle("QTL & poly")
```

## GxE

```{r}
jpeg("../../Figs/phe_qxe.jpg", width=600, height=400)
ggplot(d, aes(ENV,PHE_qxe, fill=poly)) +
  geom_point(size=3,shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  facet_wrap(~QTL)+
  scale_fill_gradient2() +
  ggtitle("QTL x ENV interaction")
dev.off()
```

```{r}
jpeg("../../Figs/phe_gxe.jpg", width=600, height=400)
ggplot(d, aes(ENV,PHE_gxe, fill=poly)) +
  geom_point(size=3,shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  facet_wrap(~QTL)+
  scale_fill_gradient2() +
  ggtitle("poly x ENV interaction")
dev.off()
```

```{r}
ggplot(d, aes(poly, ENV, fill=PHE_gxe)) +
  geom_point(size=3, shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  facet_wrap(~QTL)+
  scale_fill_gradient2() +
  ggtitle("poly x ENV interaction")
```

```{r}
ggplot(d, aes(PHE_gxe,ENV*poly, fill=poly)) +
  geom_point(size=3,shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  facet_wrap(~QTL)+
  scale_fill_gradient2() +
  ggtitle("poly x ENV interaction")
```
