---
title: "sim_phe_gen"
author: "Brian S. Yandell"
date: "1/1/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Simulate phenotype and genotype idea.

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
```

```{r}
n <- 200
sd <- 0
env <- rnorm(n)
qtl_num <- round(runif(n))
gwa <- rnorm(n)
err <- sd * rnorm(n)
d <- data.frame(env,qtl_num,gwa,err)
d$phe <- d$env + 2 * d$qtl_num + d$gwa + d$err
d$phe_qxe <- 2 * d$env * d$qtl_num + d$gwa + d$err
d$phe_gxe <- sqrt(2) * d$env * d$gwa + d$qtl_num + d$err
```

```{r}
d <- mutate(d, qtl = c("AA","AB")[1 + round(qtl_num)])
```

```{r}
ggplot(d, aes(phe,sort(env))) +
  geom_point(size=3) +
  geom_smooth(method="lm",se=FALSE)
```


```{r}
ggplot(d, aes(phe,env)) +
  geom_point(size=3) +
  geom_smooth(method="lm",se=FALSE)
```


```{r}
ggplot(d, aes(phe,env, fill=qtl)) +
  geom_point(size=3, shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  ggtitle("single QTL")
```

```{r}
ggplot(d, aes(phe,env, fill=gwa)) +
  geom_point(size=3, shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  scale_fill_gradient2() +
  ggtitle("GWA")
```

```{r}
ggplot(d, aes(phe,env, fill=gwa)) +
  geom_point(size=3,shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  facet_wrap(~qtl)+
  scale_fill_gradient2() +
  ggtitle("QTL & GWA")
```

```{r}
ggplot(d, aes(phe,gwa, fill=env)) +
  geom_point(size=3, shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  facet_wrap(~qtl)+
  scale_fill_gradient2() +
  ggtitle("QTL & GWA")
```

```{r}
ggplot(d, aes(gwa,env, fill=phe)) +
  geom_point(size=3, shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  facet_wrap(~qtl)+
  scale_fill_gradient2() +
  ggtitle("QTL & GWA")
```

## GxE

```{r}
ggplot(d, aes(phe_qxe,env, fill=gwa)) +
  geom_point(size=3,shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  facet_wrap(~qtl)+
  scale_fill_gradient2() +
  ggtitle("QTl x ENV interaction")
```

```{r}
ggplot(d, aes(phe_gxe,env, fill=gwa)) +
  geom_point(size=3,shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  facet_wrap(~qtl)+
  scale_fill_gradient2() +
  ggtitle("GWA x ENV interaction")
```

```{r}
ggplot(d, aes(gwa,env, fill=phe_gxe)) +
  geom_point(size=3, shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  facet_wrap(~qtl)+
  scale_fill_gradient2() +
  ggtitle("GWA x ENV interaction")
```

```{r}
ggplot(d, aes(phe_gxe,env*gwa, fill=gwa)) +
  geom_point(size=3,shape=21) +
  geom_smooth(method="lm",se=FALSE) +
  facet_wrap(~qtl)+
  scale_fill_gradient2() +
  ggtitle("GWA x ENV interaction")
```
